on: push
name: Publish to Factorio mod portal
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish skins-factored
      uses: Penguin-Spy/factorio-mod-portal-publish@master
      env:
        FACTORIO_MOD_API_KEY: ${{ secrets.FACTORIO_MOD_API_KEY }}
